sonar.projectKey=petfoodtn
sonar.projectName=PetfoodTN
sonar.projectVersion=1.0

sonar.sources=src,fastapi_service/app
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js,mobile_app/**,backend/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.version=3.12

sonar.sourceEncoding=UTF-8
