listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# WebSocket (debug / dashboards)
listener 9001
protocol websockets

# Topics PetfoodTN :
#   petfood/feeder/{deviceId}/status
#   petfood/esp32cam/{deviceId}/frame
#   petfood/sensor/{deviceId}/telemetry
