/**
 * Catalogue des fonctionnalités entreprise PetfoodTN — IA, ML, sécurité, BI, ISO, environnement.
 */

export const ENTERPRISE_DOMAINS = [
  {
    id: 'ia-sante',
    label: 'IA & Santé animale',
    icon: '🩺',
    color: '#0f766e',
    features: [
      {
        id: 'vet-chatbot',
        label: 'Chatbot vétérinaire intelligent 24h/24',
        description: 'Assistant IA santé animale, tri des symptômes et orientation vers téléconsultation.',
        route: '/client-vet-intelligence',
        roles: ['client', 'visitor'],
        status: 'implemented',
      },
      {
        id: 'review-analysis',
        label: 'Analyse des avis clients (satisfaction)',
        description: 'Sentiment, thèmes (qualité, livraison, emballage) et score de satisfaction.',
        route: '/admin/reviews',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'personalized-diet',
        label: 'Régimes alimentaires personnalisés',
        description: 'Génération automatique de rations, menus hebdo et nutrition thérapeutique par profil animal.',
        route: '/pet-adaptive-nutrition',
        roles: ['client'],
        status: 'implemented',
      },
    ],
  },
  {
    id: 'ml',
    label: 'Machine Learning (ML)',
    icon: '🤖',
    color: '#7c3aed',
    features: [
      {
        id: 'sales-forecast',
        label: 'Prévision des ventes futures',
        description: 'Modèles XGBoost et tendances marché pour anticiper la demande.',
        route: '/admin/advanced-ai',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'stock-rupture',
        label: 'Prédiction des ruptures de stock',
        description: 'Vélocité de vente, seuils et réapprovisionnement intelligent.',
        route: '/admin/stock-bi',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'anomaly-behavior',
        label: 'Détection comportements d\'achat inhabituels',
        description: 'Isolation Forest, fraude et anomalies IoT / commandes.',
        route: '/admin/incidents-ml',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'top-products',
        label: 'Classification produits les plus populaires',
        description: 'Top ventes, potentiel produit et segmentation clients.',
        route: '/admin/analytics-decision',
        roles: ['admin'],
        status: 'implemented',
      },
    ],
  },
  {
    id: 'big-data',
    label: 'Big Data',
    icon: '📊',
    color: '#f59e0b',
    features: [
      {
        id: 'orders-processing',
        label: 'Traitement massif des commandes',
        description: 'Kafka + Spark — milliers de commandes analysées en temps réel.',
        route: '/big-data',
        roles: ['admin', 'visitor'],
        status: 'implemented',
      },
      {
        id: 'iot-streaming',
        label: 'Flux IoT temps réel',
        description: 'MQTT → Kafka → Spark — télémétrie distributeurs, fontaines et capteurs.',
        route: '/big-data',
        roles: ['admin', 'client'],
        status: 'implemented',
        anchor: 'kafka',
      },
      {
        id: 'client-behavior',
        label: 'Analyse comportements clients',
        description: 'Spark Structured Streaming — navigation, paniers et réachat.',
        route: '/big-data',
        roles: ['admin'],
        status: 'implemented',
        anchor: 'spark',
      },
      {
        id: 'esp32cam-storage',
        label: 'Stockage images ESP32-CAM',
        description: 'Hadoop HDFS + MinIO — grandes quantités d\'images qualité alimentaire.',
        route: '/big-data',
        roles: ['admin'],
        status: 'implemented',
        anchor: 'hadoop',
      },
    ],
  },
  {
    id: 'security',
    label: 'Cybersécurité',
    icon: '🔐',
    color: '#dc2626',
    features: [
      {
        id: 'security-framework',
        label: 'Cadre de sécurité (12 piliers)',
        description: 'Authentification, RBAC, attaques web, paiement, chiffrement, IA, audit, API, cloud, surveillance, blockchain.',
        route: '/admin/security-framework',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'jwt-refresh',
        label: 'JWT avec renouvellement automatique des tokens',
        description: 'Refresh token, expiration session et bannière de reconnexion.',
        route: '/admin/intelligent-security',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: '2fa',
        label: 'Authentification à deux facteurs (2FA)',
        description: 'TOTP, codes de secours et activation par compte.',
        route: '/admin/intelligent-security',
        roles: ['admin'],
        status: 'implemented',
        anchor: '2fa',
      },
      {
        id: 'bcrypt',
        label: 'Chiffrement mots de passe (BCrypt)',
        description: 'Hachage sécurisé côté serveur — politique de mots de passe forts (8+ car.).',
        route: '/admin/security-framework',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'sql-xss',
        label: 'Protection SQL Injection & XSS',
        description: 'IDS, scan corps API et filtrage automatique des contenus.',
        route: '/admin/security',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'database-security',
        label: 'Sécurité base de données PostgreSQL',
        description: 'TLS, Prisma ORM, chiffrement, rôles d\'accès et journal anti-injection.',
        route: '/admin/database-security',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'activity-logs',
        label: 'Journalisation activités sensibles',
        description: 'Audit trail connexions, modifications et actions admin.',
        route: '/admin/activity-logs',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'backups',
        label: 'Sauvegardes automatiques sécurisées',
        description: 'Snapshots planifiés, chiffrement et restauration.',
        route: '/admin/backups',
        roles: ['admin'],
        status: 'implemented',
      },
    ],
  },
  {
    id: 'bi',
    label: 'Business Intelligence (BI)',
    icon: '📊',
    color: '#1e40af',
    features: [
      {
        id: 'bi-dashboard',
        label: 'Tableau de bord décisionnel interactif',
        description: 'KPIs temps réel, graphiques et alertes métier.',
        route: '/admin/dashboard',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'realtime-sales',
        label: 'Analyse des ventes en temps réel',
        description: 'Flux commandes, CA et statuts livraison.',
        route: '/admin/sales',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'kpi-suite',
        label: 'Indicateurs KPI (CA, commandes, top produits, satisfaction)',
        description: 'Chiffre d\'affaires, volume commandes, best-sellers et NPS.',
        route: '/admin/business-intelligence',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'pdf-excel',
        label: 'Rapports PDF et Excel automatiques',
        description: 'Export ventes, IoT, vétérinaire, satisfaction — CSV, Excel, PDF.',
        route: '/admin/reports',
        roles: ['admin'],
        status: 'implemented',
      },
      {
        id: 'geo-sales',
        label: 'Analyse géographique des ventes',
        description: 'Répartition par gouvernorat, zones livraison et heatmap CA.',
        route: '/admin/business-intelligence',
        roles: ['admin'],
        status: 'implemented',
        anchor: 'geo',
      },
    ],
  },
  {
    id: 'iso',
    label: 'Normes ISO',
    icon: '🛡️',
    color: '#0369a1',
    features: [
      {
        id: 'iso-27001',
        label: 'ISO 27001 — sécurité de l\'information',
        description: 'Gestion des risques, accès et continuité.',
        route: '/compliance',
        roles: ['client', 'visitor'],
        status: 'implemented',
      },
      {
        id: 'iso-9001',
        label: 'ISO 9001 — gestion de la qualité',
        description: 'Processus qualité, traçabilité et amélioration continue.',
        route: '/qualite-iso',
        roles: ['client', 'visitor'],
        status: 'implemented',
      },
      {
        id: 'full-traceability',
        label: 'Traçabilité complète des opérations',
        description: 'Blockchain SHA-256, Merkle et ancrage IoT PetFoodIoT.',
        route: '/client-traceability',
        roles: ['client'],
        status: 'implemented',
      },
      {
        id: 'rbac',
        label: 'Gestion des accès basée sur les rôles (RBAC)',
        description: 'Admin, client, vétérinaire, livreur, vendeur, modérateur.',
        route: '/capabilities',
        roles: ['visitor'],
        status: 'implemented',
      },
    ],
  },
  {
    id: 'environment',
    label: 'Environnement & Développement Durable',
    icon: '🌱',
    color: '#059669',
    features: [
      {
        id: 'food-waste',
        label: 'Réduction du gaspillage alimentaire (IA)',
        description: 'Optimisation stocks, alertes péremption et redistribution.',
        route: '/compliance',
        roles: ['client', 'visitor'],
        status: 'implemented',
        anchor: 'waste',
      },
      {
        id: 'expiry-monitor',
        label: 'Surveillance des dates de péremption',
        description: 'ESP32-CAM, qualité alimentaire et alertes client/vétérinaire.',
        route: '/food-quality-surveillance',
        roles: ['client'],
        status: 'implemented',
      },
      {
        id: 'delivery-co2',
        label: 'Optimisation trajets livraison (CO₂)',
        description: 'Routes éco, regroupement colis et réduction émissions.',
        route: '/livreur/intelligence',
        roles: ['livreur'],
        status: 'implemented',
      },
      {
        id: 'eco-packaging',
        label: 'Emballages écologiques',
        description: 'Matériaux recyclables et réduction plastique.',
        route: '/compliance',
        roles: ['visitor'],
        status: 'partial',
      },
      {
        id: 'carbon-footprint',
        label: 'Empreinte carbone des livraisons',
        description: 'Statistiques CO₂, objectif −30 % et compensation.',
        route: '/compliance',
        roles: ['visitor'],
        status: 'implemented',
        anchor: 'carbon',
      },
    ],
  },
];

export const countEnterpriseFeatures = () => {
  const all = ENTERPRISE_DOMAINS.flatMap((d) => d.features);
  return {
    total: all.length,
    implemented: all.filter((f) => f.status === 'implemented').length,
    partial: all.filter((f) => f.status === 'partial').length,
  };
};

export default ENTERPRISE_DOMAINS;
