/** Base de connaissances — symptômes, maladies chroniques et traitements pets. */

export const TREATMENT_TYPES = {
  medicament: { label: 'Médicament', icon: '💊', color: '#dc2626' },
  gelule: { label: 'Gélule / comprimé', icon: '💊', color: '#7c3aed' },
  vaccin: { label: 'Vaccin', icon: '💉', color: '#2563eb' },
  antiparasitaire: { label: 'Antiparasitaire', icon: '🦟', color: '#059669' },
  complement: { label: 'Complément', icon: '🌿', color: '#d97706' },
  soin: { label: 'Soin local', icon: '🧴', color: '#0ea5e9' },
};

export const COMMON_SYMPTOMS = [
  { id: 'scratch', label: 'Grattage excessif', icon: '🐾', keywords: ['grattage', 'prurit', 'demangeaison'] },
  { id: 'vomit', label: 'Vomissements', icon: '🤢', keywords: ['vomissement', 'vomi', 'regurgitation'] },
  { id: 'diarrhea', label: 'Diarrhée', icon: '💩', keywords: ['diarrhee', 'diarrhée', 'selles molles'] },
  { id: 'limping', label: 'Boiterie', icon: '🦴', keywords: ['boite', 'boiterie', 'lame'] },
  { id: 'cough', label: 'Toux / éternuements', icon: '😷', keywords: ['toux', 'eternuement', 'ecoulement nasal'] },
  { id: 'ear', label: 'Problème oreille', icon: '👂', keywords: ['oreille', 'otite', 'secoue tete'] },
  { id: 'lethargy', label: 'Abattement / fatigue', icon: '😴', keywords: ['abattement', 'fatigue', 'lethargie', 'anorexie'] },
  { id: 'thirst', label: 'Soif excessive', icon: '💧', keywords: ['soif', 'polydipsie', 'boit beaucoup'] },
  { id: 'weight', label: 'Perte / prise de poids', icon: '⚖️', keywords: ['maigre', 'perte poids', 'obesite', 'grossit'] },
  { id: 'fever', label: 'Fièvre', icon: '🌡️', keywords: ['fievre', 'fièvre', 'température'] },
  { id: 'skin', label: 'Rougeurs / pelage', icon: '🔴', keywords: ['rougeur', 'pelage', 'pellicules', 'alopecie'] },
  { id: 'urine', label: 'Urines fréquentes', icon: '🚽', keywords: ['urine', 'miction', 'pipi'] },
];

export const CHRONIC_DISEASES = [
  {
    id: 'dermatite-allergique',
    name: 'Dermatite allergique',
    petTypes: ['dog', 'cat'],
    chronic: true,
    symptoms: ['scratch', 'skin', 'ear'],
    keywords: ['dermatite', 'allerg', 'prurit', 'atopie'],
    description: 'Inflammation cutanée récurrente — allergies alimentaires ou environnementales.',
    monitoring: 'Surveiller grattage, lésions cutanées et otites récidivantes.',
  },
  {
    id: 'arthrose',
    name: 'Arthrose',
    petTypes: ['dog', 'cat'],
    chronic: true,
    symptoms: ['limping', 'lethargy'],
    keywords: ['arthrose', 'arthrite', 'articulation', 'raideur'],
    description: 'Usure cartilagineuse — douleur et raideur, surtout chez les animaux âgés ou obèses.',
    monitoring: 'Contrôle mobilité, poids corporel et douleur à la palpation.',
  },
  {
    id: 'diabete',
    name: 'Diabète',
    petTypes: ['dog', 'cat'],
    chronic: true,
    symptoms: ['thirst', 'weight', 'lethargy'],
    keywords: ['diabete', 'diabète', 'glycemie', 'insuline'],
    description: 'Trouble métabolique — soif, urines fréquentes, perte de poids malgré bon appétit.',
    monitoring: 'Glycémie, poids, consommation eau — contrôle vétérinaire régulier.',
  },
  {
    id: 'insuffisance-renale',
    name: 'Insuffisance rénale chronique',
    petTypes: ['dog', 'cat'],
    chronic: true,
    symptoms: ['thirst', 'vomit', 'lethargy', 'urine'],
    keywords: ['renal', 'rein', 'creatinine', 'irc'],
    description: 'Fonction rénale diminuée — fréquent chez les chats seniors.',
    monitoring: 'Analyses sanguines (créatinine, urée) tous les 3–6 mois.',
  },
  {
    id: 'hypothyroidie',
    name: 'Hypothyroïdie',
    petTypes: ['dog'],
    chronic: true,
    symptoms: ['weight', 'lethargy', 'skin'],
    keywords: ['thyroide', 'hypothyroïdie', 'lethargie'],
    description: 'Déficit hormonal thyroïdien — prise de poids, pelage terne, fatigue.',
    monitoring: 'T4 libre — ajustement posologie Lévothyrox.',
  },
  {
    id: 'cardiaque',
    name: 'Insuffisance cardiaque',
    petTypes: ['dog', 'cat'],
    chronic: true,
    symptoms: ['cough', 'lethargy'],
    keywords: ['cardiaque', 'coeur', 'souffle', 'toux nocturne'],
    description: 'Maladie cardiaque dégénérative — toux, essoufflement, intolérance à l\'effort.',
    monitoring: 'Échocardiographie et suivi médicamenteux strict.',
  },
  {
    id: 'obesite',
    name: 'Obésité',
    petTypes: ['dog', 'cat'],
    chronic: true,
    symptoms: ['weight', 'lethargy', 'limping'],
    keywords: ['obesite', 'obésité', 'surpoids', 'bcs'],
    description: 'Excès de poids — facteur aggravant arthrose, diabète et cardiaque.',
    monitoring: 'Courbe de poids, score corporel (BCS), ration alimentaire.',
  },
];

export const TREATMENT_PROTOCOLS = [
  {
    id: 'tx-derm-antihist',
    diseases: ['Dermatite allergique', 'dermatite-allergique'],
    type: 'medicament',
    name: 'Antihistaminique vétérinaire',
    dosage: 'Selon poids (<4 kg : ½ cp)',
    frequency: '1×/jour',
    duration: '14 jours',
    petTypes: ['dog', 'cat'],
    rationale: 'Réduction prurit — en association avec shampoing apaisant.',
    priority: 'medium',
    otc: false,
  },
  {
    id: 'tx-derm-shampoo',
    diseases: ['Dermatite allergique'],
    type: 'soin',
    name: 'Shampoing dermatologique',
    dosage: '1 bain',
    frequency: '2×/semaine',
    duration: '21 jours',
    petTypes: ['dog', 'cat'],
    rationale: 'Apaisement cutané — complément au traitement médical.',
    priority: 'low',
    otc: true,
  },
  {
    id: 'tx-arthrose-ains',
    diseases: ['Arthrose', 'arthrose'],
    type: 'gelule',
    name: 'Anti-inflammatoire chien (AINS)',
    dosage: '1 cp / 20 kg',
    frequency: '1×/jour',
    duration: '10 jours',
    petTypes: ['dog'],
    rationale: 'Douleur articulaire — contrepulsion gastrique si risque digestif.',
    priority: 'high',
    otc: false,
  },
  {
    id: 'tx-arthrose-omega',
    diseases: ['Arthrose', 'arthrose'],
    type: 'complement',
    name: 'Oméga-3 articulaires',
    dosage: '1 capsule/j',
    frequency: '1×/jour',
    duration: '30 jours',
    petTypes: ['dog', 'cat'],
    rationale: 'Soutien cartilage et mobilité — traitement de fond.',
    priority: 'medium',
    otc: true,
  },
  {
    id: 'tx-diabete-insuline',
    diseases: ['Diabète', 'diabete'],
    type: 'medicament',
    name: 'Insuline vétérinaire',
    dosage: 'Selon protocole vétérinaire',
    frequency: '2×/jour',
    duration: 'Chronique',
    petTypes: ['dog', 'cat'],
    rationale: 'Prescription obligatoire — titration sous contrôle glycémique.',
    priority: 'high',
    otc: false,
  },
  {
    id: 'tx-renal-diet',
    diseases: ['Insuffisance rénale chronique', 'insuffisance-renale'],
    type: 'complement',
    name: 'Alimentation rénale thérapeutique',
    dosage: 'Ration quotidienne adaptée',
    frequency: 'Continu',
    duration: 'Chronique',
    petTypes: ['dog', 'cat'],
    rationale: 'Réduction charge phosphore et protéines de haute qualité.',
    priority: 'high',
    otc: true,
  },
  {
    id: 'tx-gastro-probio',
    diseases: ['Gastro-entérite', 'Infection digestive'],
    type: 'gelule',
    name: 'Probiotique intestinal',
    dosage: '1 sachet',
    frequency: '1×/jour',
    duration: '7 jours',
    petTypes: ['dog', 'cat'],
    rationale: 'Rééquilibrage flore après épisode digestif aigu.',
    priority: 'medium',
    otc: true,
  },
  {
    id: 'tx-otite-collyre',
    diseases: ['Otite'],
    type: 'soin',
    name: 'Collyre auriculaire antibiotique',
    dosage: '2 gouttes / oreille',
    frequency: '2×/jour',
    duration: '10 jours',
    petTypes: ['dog', 'cat'],
    rationale: 'Otite externe — nettoyage préalable du conduit auditif.',
    priority: 'high',
    otc: false,
  },
  {
    id: 'tx-resp-amox',
    diseases: ['Typhus / Coryza', 'Infection respiratoire'],
    type: 'medicament',
    name: 'Amoxicilline 500 mg',
    dosage: '12 mg/kg',
    frequency: '2×/12h',
    duration: '10 jours',
    petTypes: ['cat'],
    rationale: 'Infection respiratoire féline — protocole antibiotique standard.',
    priority: 'high',
    otc: false,
  },
  {
    id: 'tx-parasite-pipette',
    diseases: ['Parasites externes'],
    type: 'antiparasitaire',
    name: 'Pipette antiparasitaire externe',
    dosage: '1 pipette',
    frequency: '1×/mois',
    duration: 'Continu',
    petTypes: ['dog', 'cat'],
    rationale: 'Prévention puces et tiques — traitement mensuel.',
    priority: 'medium',
    otc: true,
  },
  {
    id: 'tx-parasite-vermifuge',
    diseases: ['Parasites externes', 'Infection digestive'],
    type: 'gelule',
    name: 'Vermifuge large spectre',
    dosage: 'Selon poids',
    frequency: '1×/3 mois',
    duration: '1 dose',
    petTypes: ['dog', 'cat'],
    rationale: 'Déparasitage interne régulier — coproscopie si doute.',
    priority: 'medium',
    otc: true,
  },
];

export const VACCINE_SCHEDULE = [
  {
    id: 'vac-rage',
    name: 'Vaccin Rage',
    petTypes: ['dog', 'cat'],
    frequency: 'Annuel',
    mandatory: true,
    description: 'Obligatoire en Tunisie — rappel annuel.',
    nextDueDays: 45,
  },
  {
    id: 'vac-chppi',
    name: 'CHPPi + Leptospirose (chien)',
    petTypes: ['dog'],
    frequency: 'Annuel',
    mandatory: false,
    description: 'Primo-vaccination puis rappel annuel.',
    nextDueDays: 120,
  },
  {
    id: 'vac-typhus',
    name: 'Typhus / Coryza / Leucose (chat)',
    petTypes: ['cat'],
    frequency: 'Annuel',
    mandatory: false,
    description: 'Protocole chaton puis rappels annuels.',
    nextDueDays: 90,
  },
  {
    id: 'vac-parvovirose',
    name: 'Parvovirose + Maladie de Carré',
    petTypes: ['dog'],
    frequency: 'Primo + rappels',
    mandatory: false,
    description: 'Essentiel chiots — protocole vétérinaire standard.',
    nextDueDays: 180,
  },
];

export default {
  TREATMENT_TYPES,
  COMMON_SYMPTOMS,
  CHRONIC_DISEASES,
  TREATMENT_PROTOCOLS,
  VACCINE_SCHEDULE,
};
