/**
 * Catalogue officiel des services PetfoodTN — source unique pour navigation, hub et docs.
 */

export const PLATFORM_SERVICE_CATEGORIES = [
  { id: 'boutique', label: 'Boutique & achats', icon: '🛒' },
  { id: 'sante', label: 'Santé & vétérinaire', icon: '🩺' },
  { id: 'nutrition', label: 'Nutrition & bien-être', icon: '🥗' },
  { id: 'soins', label: 'Soins réservables', icon: '✂️' },
  { id: 'iot', label: 'IoT & smart pet', icon: '📡' },
  { id: 'livraison', label: 'Livraison & logistique', icon: '🚚' },
  { id: 'ecosystem', label: 'Écosystème & premium', icon: '🌿' },
  { id: 'ia', label: 'IA & analytics', icon: '🤖' },
  { id: 'admin', label: 'Administration', icon: '⚙️' },
  { id: 'livreur', label: 'Livraison (livreur)', icon: '🛵' },
  { id: 'vet', label: 'Espace vétérinaire', icon: '🏥' },
  { id: 'vendeur', label: 'Vendeur marketplace', icon: '🏬' },
  { id: 'moderateur', label: 'Modération', icon: '🛡️' },
];

/** @type {Array<{
 *   id: string;
 *   category: string;
 *   roles: string[];
 *   label: string;
 *   description: string;
 *   route: string;
 *   icon: string;
 *   api?: string;
 *   serviceKey?: string;
 *   bookable?: boolean;
 *   badge?: string;
 * }>} */
export const PLATFORM_SERVICES = [
  // —— Boutique (client) ——
  {
    id: 'products',
    category: 'boutique',
    roles: ['client'],
    label: 'Boutique produits',
    description: 'Croquettes, accessoires, aliments NAC — filtres par espèce et recommandations IA.',
    route: '/client-products',
    icon: '🏷️',
    api: 'GET /api/products',
    serviceKey: 'productService',
  },
  {
    id: 'orders',
    category: 'boutique',
    roles: ['client'],
    label: 'Mes commandes',
    description: 'Suivi des commandes, statut livraison et historique.',
    route: '/client-orders',
    icon: '📦',
    api: 'GET /api/orders',
    serviceKey: 'orderService',
  },
  {
    id: 'invoices',
    category: 'boutique',
    roles: ['client'],
    label: 'Factures',
    description: 'Factures PDF, paiements et justificatifs.',
    route: '/client-invoices',
    icon: '🧾',
    api: 'GET /api/invoices',
    serviceKey: 'orderService',
  },
  {
    id: 'favorites',
    category: 'boutique',
    roles: ['client'],
    label: 'Favoris',
    description: 'Produits sauvegardés pour rachat rapide.',
    route: '/client-favorites',
    icon: '❤️',
    api: 'GET /api/favorites',
    serviceKey: 'favoriteService',
  },
  {
    id: 'loyalty',
    category: 'boutique',
    roles: ['client'],
    label: 'Programme fidélité',
    description: 'Points, récompenses et offres personnalisées.',
    route: '/client-loyalty',
    icon: '🎁',
    api: 'GET /api/loyalty',
    serviceKey: 'loyaltyService',
  },
  {
    id: 'traceability',
    category: 'iot',
    roles: ['client'],
    label: 'Traçabilité blockchain',
    description: 'Origine des lots, chaîne d\'approvisionnement et vérification.',
    route: '/client-traceability',
    icon: '🔗',
    api: 'GET /api/ecosystem/traceability',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'platform-compliance',
    category: 'ecosystem',
    roles: ['client'],
    label: 'Conformité ISO & environnement',
    description: 'Normes ISO, certifications mondiales, engagements écologiques et audits qualité.',
    route: '/compliance',
    icon: '🛡️',
    api: 'GET /api/platform/compliance',
    serviceKey: 'platformComplianceEngine',
    badge: 'ISO',
  },
  {
    id: 'checkout',
    category: 'boutique',
    roles: ['client'],
    label: 'Paiement & wallet',
    description: 'Stripe, PayPal, portefeuille PetfoodTN.',
    route: '/checkout',
    icon: '💳',
    api: 'POST /api/stripe, /api/payments',
    serviceKey: 'walletService',
  },

  // —— Santé ——
  {
    id: 'veterinary',
    category: 'sante',
    roles: ['client'],
    label: 'Santé & vétérinaire',
    description: 'Prise de RDV, vaccins, rappels et dossier de santé.',
    route: '/veterinary',
    icon: '🩺',
    api: 'GET /api/veterinary',
    serviceKey: 'vetService',
  },
  {
    id: 'client-pets',
    category: 'sante',
    roles: ['client'],
    label: 'Mes animaux',
    description: 'Profils compagnons — race, poids, allergies, puce électronique.',
    route: '/client-pets',
    icon: '🐾',
    api: 'GET /api/pets',
    serviceKey: 'petService',
  },
  {
    id: 'medical-dossier',
    category: 'sante',
    roles: ['client'],
    label: 'Dossier médical',
    description: 'Historique consultations, ordonnances et vaccinations.',
    route: '/medical-dossier',
    icon: '📁',
    api: 'GET /api/users/pets',
    serviceKey: 'userService',
  },
  {
    id: 'found-me',
    category: 'sante',
    roles: ['client'],
    label: 'Retrouvé Moi',
    description: 'Alerte animal perdu, QR code et signalements communautaires.',
    route: '/found-me',
    icon: '🔍',
    api: 'GET /api/found-me',
    serviceKey: 'foundMeService',
  },
  {
    id: 'vaccine-reminders',
    category: 'sante',
    roles: ['client'],
    label: 'Rappels vaccins',
    description: 'Notifications automatiques avant échéance vaccinale.',
    route: '/medical-dossier',
    icon: '💉',
    api: 'GET /api/vaccine-reminders',
    serviceKey: 'vaccineReminderService',
  },

  // —— Nutrition ——
  {
    id: 'pet-nutrition',
    category: 'nutrition',
    roles: ['client'],
    label: 'Nutrition par animal',
    description: 'Calories, races tunisiennes, chiens, chats, oiseaux, NAC, reptiles.',
    route: '/pet-calories',
    icon: '🥗',
    api: 'GET /api/pets/nutrition',
    serviceKey: 'petNutritionService',
    badge: 'Multi-espèces',
  },
  {
    id: 'pet-intelligent-nutrition',
    category: 'nutrition',
    roles: ['client'],
    label: 'Profil nutritionnel IA',
    description: 'Profil dynamique, score PetFoodTN, analyse ingrédients, menus, journal, transition, thérapeutique et prédictions.',
    route: '/pet-adaptive-nutrition',
    icon: '🧬',
    api: 'GET /api/pets/nutrition/adaptive',
    serviceKey: 'adaptiveNutritionService',
    badge: 'IA',
  },
  {
    id: 'digital-nutrition-twin',
    category: 'nutrition',
    roles: ['client'],
    label: 'Digital Nutrition Twin',
    description: 'Simule l\'impact d\'un changement alimentaire sur poids, calories, équilibre nutritionnel et risques santé.',
    route: '/client-digital-twin',
    icon: '🧬',
    api: 'GET /api/pets/nutrition/twin',
    serviceKey: 'digitalTwinService',
    badge: 'Simulation',
  },
  {
    id: 'pet-advice',
    category: 'nutrition',
    roles: ['client'],
    label: 'Conseils pour pets',
    description: 'Guides alimentation, soins et comportement par espèce.',
    route: '/pet-advice',
    icon: '💡',
    serviceKey: 'userService',
  },
  {
    id: 'smart-water',
    category: 'iot',
    roles: ['client'],
    label: 'Fontaine connectée',
    description: 'Suivi hydratation, rappels et courbes de consommation.',
    route: '/client-smart-water',
    icon: '💧',
    api: 'GET /api/ecosystem/water-monitor',
    serviceKey: 'ecosystemService',
  },

  // —— Soins réservables ——
  {
    id: 'grooming',
    category: 'soins',
    roles: ['client'],
    label: 'Toilettage',
    description: 'Coupe, brossage et soins du pelage — créneaux en ligne.',
    route: '/client-services?type=grooming',
    icon: '✂️',
    api: 'POST /api/service-bookings',
    serviceKey: 'serviceBookingService',
    bookable: true,
  },
  {
    id: 'boarding',
    category: 'soins',
    roles: ['client'],
    label: 'Pension & garde',
    description: 'Pension, garde à domicile et garderie journée.',
    route: '/client-services?type=boarding',
    icon: '🏠',
    api: 'POST /api/service-bookings',
    serviceKey: 'serviceBookingService',
    bookable: true,
  },
  {
    id: 'training',
    category: 'soins',
    roles: ['client'],
    label: 'Dressage',
    description: 'Éducation positive — chiot, rappel, socialisation.',
    route: '/client-services?type=training',
    icon: '🎓',
    api: 'POST /api/service-bookings',
    serviceKey: 'serviceBookingService',
    bookable: true,
  },
  {
    id: 'wellness-pack',
    category: 'soins',
    roles: ['client'],
    label: 'Forfait bien-être',
    description: 'Toilettage + bain + griffes avec réduction pack.',
    route: '/client-services?type=wellness_pack',
    icon: '✨',
    api: 'POST /api/service-bookings',
    serviceKey: 'serviceBookingService',
    bookable: true,
    badge: '-10 %',
  },
  {
    id: 'rehabilitation',
    category: 'soins',
    roles: ['client'],
    label: 'Réhabilitation refuges',
    description: 'Soutien refuges partenaires et adoption.',
    route: '/client-services',
    icon: '💚',
    api: 'GET /api/ecosystem/rehabilitation',
    serviceKey: 'ecosystemService',
  },

  // —— IoT ——
  {
    id: 'client-iot',
    category: 'iot',
    roles: ['client'],
    label: 'Centre IoT',
    description: 'Tableau de bord unifié : distributeur, fontaine, livraison et traçabilité.',
    route: '/client-iot',
    icon: '📡',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'client-esp32cam-food-quality',
    category: 'iot',
    roles: ['client'],
    label: 'ESP32-CAM qualité croquettes',
    description: 'Détection temps réel : couleur, moisissure, température et humidité du bac.',
    route: '/client-iot?tab=food-quality',
    icon: '📷',
    api: 'GET /api/client/iot/food-quality',
    serviceKey: 'iotFoodQualityService',
  },
  {
    id: 'pet-feeder',
    category: 'iot',
    roles: ['client'],
    label: 'Distributeur IoT',
    description: 'Portions automatiques, horaires et alertes niveau croquettes.',
    route: '/pet-feeder',
    icon: '🍽️',
    api: 'GET /api/feeder',
    serviceKey: 'feederFirebaseService',
  },
  {
    id: 'hardware-pcb',
    category: 'iot',
    roles: ['client'],
    label: 'Cartes PCB & alimentation',
    description: 'PCB contrôle ESP32 et carte PSU 5 V — schémas, BOM, ARES et export Gerber.',
    route: '/client-hardware-pcb',
    icon: '🟢',
    badge: 'ARES',
  },

  // —— Livraison client ——
  {
    id: 'store-locator',
    category: 'livraison',
    roles: ['client'],
    label: 'Magasin le plus proche',
    description: 'Carte des points de vente et horaires.',
    route: '/store-locator',
    icon: '📍',
    serviceKey: 'userService',
  },
  {
    id: 'relay-points',
    category: 'livraison',
    roles: ['client'],
    label: 'Points relais',
    description: 'Retrait commande en point relais partenaire.',
    route: '/veterinary',
    icon: '📫',
    api: 'GET /api/ecosystem/relay-points',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'smart-delivery',
    category: 'livraison',
    roles: ['client'],
    label: 'Livraison prédictive',
    description: 'Créneaux optimisés et suivi temps réel.',
    route: '/client-smart-delivery',
    icon: '🚚',
    api: 'GET /api/ecosystem/delivery/live',
    serviceKey: 'ecosystemService',
  },

  // —— Écosystème premium ——
  {
    id: 'pet-passport',
    category: 'ecosystem',
    roles: ['client'],
    label: 'Passeport animal',
    description: 'Identité numérique, vaccins et voyages.',
    route: '/client-pet-passport',
    icon: '🛂',
    api: 'GET /api/ecosystem/pet-passport',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'subscriptions',
    category: 'ecosystem',
    roles: ['client'],
    label: 'Abonnements croquettes',
    description: 'Livraison récurrente et budget mensuel.',
    route: '/client-products',
    icon: '🔁',
    api: 'GET /api/ecosystem/subscriptions',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'marketplace',
    category: 'ecosystem',
    roles: ['client', 'admin'],
    label: 'Marketplace fournisseurs',
    description: 'Produits vendeurs tiers certifiés PetfoodTN.',
    route: '/client-products',
    icon: '🏬',
    api: 'GET /api/ecosystem/marketplace',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'shelters',
    category: 'ecosystem',
    roles: ['client'],
    label: 'Refuges & adoption',
    description: 'Animaux à adopter et demandes en ligne.',
    route: '/client-services',
    icon: '🐾',
    api: 'GET /api/ecosystem/shelters',
    serviceKey: 'ecosystemService',
  },

  // —— IA ——
  {
    id: 'chat-assistant',
    category: 'ia',
    roles: ['client', 'admin', 'vet', 'livreur'],
    label: 'Assistant IA (Groq)',
    description: 'Chat conseil produits, nutrition et services.',
    route: '#chat',
    icon: '🤖',
    api: 'POST /api/chat/message',
    serviceKey: 'chatService',
  },
  {
    id: 'ml-recommendations-hybrid',
    category: 'ia',
    roles: ['client', 'vet', 'admin', 'livreur', 'moderator', 'vendor'],
    label: 'Recommandations hybrides IA',
    description: 'Contenu + collaboratif + filtre NLP avis (FastAPI).',
    route: '/client-recommendations',
    icon: '🎯',
    api: 'GET /api/recommendations/hybrid',
    serviceKey: 'hybridRecommendationService',
  },
  {
    id: 'ml-recommendations-search',
    category: 'ia',
    roles: ['admin', 'moderator'],
    label: 'Recherche produits par avis NLP',
    description: 'Filtre catalogue selon commentaires clients et note minimale.',
    route: '/admin/recommendations',
    icon: '🔍',
    api: 'GET /api/recommendations/search',
    serviceKey: 'hybridRecommendationService',
  },
  {
    id: 'ml-recommendations-admin-client',
    category: 'admin',
    roles: ['admin'],
    label: 'Recommandations par client (admin)',
    description: 'Profil animal, historique achats et similarité utilisateurs.',
    route: '/admin/recommendations',
    icon: '👤',
    api: 'GET /api/recommendations/admin/client/:userId',
    serviceKey: 'hybridRecommendationService',
  },
  {
    id: 'ml-recommendations',
    category: 'ia',
    roles: ['client'],
    label: 'Recommandations IA (legacy)',
    description: 'Alias — utiliser GET /api/recommendations/hybrid (moteur hybride NLP).',
    route: '/client-recommendations',
    icon: '🎯',
    api: 'GET /api/recommendations/hybrid',
    serviceKey: 'hybridRecommendationService',
  },
  {
    id: 'emotion-analysis',
    category: 'ia',
    roles: ['client'],
    label: 'Analyse émotions',
    description: 'Détection stress/confort via photo ou vidéo.',
    route: '/client-reviews',
    icon: '😺',
    api: 'POST /api/ecosystem/emotion/analyze',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'vet-chat-24',
    category: 'ia',
    roles: ['client'],
    label: 'Vétérinaire IA 24/7',
    description: 'Premiers conseils santé avant RDV clinique.',
    route: '/veterinary',
    icon: '💬',
    api: 'POST /api/ecosystem/vet-chat',
    serviceKey: 'ecosystemService',
  },

  // —— Admin ——
  {
    id: 'admin-dashboard',
    category: 'admin',
    roles: ['admin'],
    label: 'Dashboard admin',
    description: 'KPIs, CA, commandes et alertes ML.',
    route: '/admin/dashboard',
    icon: '📈',
    api: 'GET /api/ml/admin/insights',
    serviceKey: 'mlService',
  },
  {
    id: 'admin-nlp-models',
    category: 'admin',
    roles: ['admin'],
    label: 'Modèles NLP (BERT / LSTM / GRU)',
    description: 'Sélection du modèle de prédiction texte selon métriques F1, précision, rappel.',
    route: '/admin/nlp-models',
    icon: '🧠',
    api: 'GET /api/ml/admin/nlp-models/benchmark',
    serviceKey: 'nlpModelService',
  },
  {
    id: 'admin-orders',
    category: 'admin',
    roles: ['admin'],
    label: 'Gestion commandes',
    description: 'Validation, annulation, risque ML et assignation livreur.',
    route: '/admin/orders',
    icon: '📦',
    api: 'GET /api/orders',
    serviceKey: 'orderService',
  },
  {
    id: 'admin-vendors',
    category: 'admin',
    roles: ['admin'],
    label: 'Fournisseurs',
    description: 'Onboarding, suspension et stats marketplace.',
    route: '/admin/vendors',
    icon: '🏬',
    api: 'GET /api/ecosystem/admin/vendors',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'admin-moderators',
    category: 'admin',
    roles: ['admin'],
    label: 'Modérateurs',
    description: 'Création, suspension et supervision des comptes modération.',
    route: '/admin/moderators',
    icon: '🛡️',
    api: 'GET /api/admin/moderators',
    serviceKey: 'adminService',
  },
  {
    id: 'admin-refunds',
    category: 'admin',
    roles: ['admin'],
    label: 'Remboursements',
    description: 'Historique, politique globale, remboursement forcé et annulation.',
    route: '/admin/refunds',
    icon: '💸',
    api: 'GET /api/admin/refunds',
    serviceKey: 'refundService',
  },
  {
    id: 'admin-system',
    category: 'admin',
    roles: ['admin'],
    label: 'Configuration globale système',
    description: 'Paramètres plateforme, sécurité, marketplace, livraison et intégrations.',
    route: '/admin/system',
    icon: '🔧',
    api: 'GET /api/admin/system/config',
    serviceKey: 'adminService',
  },
  {
    id: 'admin-activity-logs',
    category: 'admin',
    roles: ['admin'],
    label: 'Journaux d\'activité',
    description: 'Historique des actions — tous acteurs, export JSON/CSV.',
    route: '/admin/activity-logs',
    icon: '📋',
    api: 'GET /api/admin/activity-logs',
    serviceKey: 'activityLogService',
  },
  {
    id: 'admin-digital-marketing',
    category: 'admin',
    roles: ['admin'],
    label: 'Marketing digital',
    description: 'Acquisition, campagnes multicanal, SEO, social et newsletter.',
    route: '/admin/digital-marketing',
    icon: '📣',
    api: 'GET /api/admin/marketing/pack',
    serviceKey: 'digitalMarketingService',
  },
  {
    id: 'admin-stock-bi',
    category: 'admin',
    roles: ['admin'],
    label: 'Stock BI',
    description: 'Prévisions stock, ruptures et réapprovisionnement.',
    route: '/admin/stock-bi',
    icon: '📊',
    api: 'GET /api/admin/stock-bi/pack',
    serviceKey: 'adminOpsService',
  },
  {
    id: 'admin-food-quality',
    category: 'admin',
    roles: ['admin'],
    label: 'Surveillance qualité alimentaire',
    description: 'Chaîne du froid IoT, anomalies IA, scores lots et réfrigérateurs connectés.',
    route: '/admin/food-quality',
    icon: '🌡️',
    api: 'GET /api/admin/food-quality/surveillance',
    serviceKey: 'coldChainQualityService',
  },
  {
    id: 'admin-delivery-cold-chain',
    category: 'admin',
    roles: ['admin'],
    label: 'Livraison chaîne du froid',
    description: 'Capteurs véhicules en transit — entrepôt jusqu\'au client final.',
    route: '/admin/delivery-cold-chain',
    icon: '🚚',
    api: 'GET /api/admin/delivery/cold-chain/surveillance',
    serviceKey: 'deliveryColdChainService',
  },
  {
    id: 'admin-complaints',
    category: 'admin',
    roles: ['admin'],
    label: 'Réclamations',
    description: 'Traitement tickets clients et SLA.',
    route: '/admin/complaints',
    icon: '⚠️',
    api: 'GET /api/complaints',
    serviceKey: 'complaintService',
  },
  {
    id: 'admin-powerbi',
    category: 'admin',
    roles: ['admin'],
    label: 'Power BI',
    description: 'Rapports ventes, stocks et fidélité.',
    route: '/admin/powerbi',
    icon: '📊',
    serviceKey: 'analyticsHubService',
  },

  // —— Livreur ——
  {
    id: 'livreur-dashboard',
    category: 'livreur',
    roles: ['livreur'],
    label: 'Tableau de bord livreur',
    description: 'Tournées du jour, gains et statistiques.',
    route: '/livreur/dashboard',
    icon: '🛵',
    serviceKey: 'orderService',
  },
  {
    id: 'livreur-orders',
    category: 'livreur',
    roles: ['livreur'],
    label: 'Commandes à livrer',
    description: 'Liste, statuts et preuve de livraison.',
    route: '/livreur/orders',
    icon: '📦',
    api: 'GET /api/orders',
    serviceKey: 'orderService',
  },
  {
    id: 'livreur-route',
    category: 'livreur',
    roles: ['livreur'],
    label: 'Itinéraire optimisé',
    description: 'Carte, ordre des arrêts et ETA.',
    route: '/livreur/route',
    icon: '🗺️',
    serviceKey: 'orderService',
  },
  {
    id: 'livreur-intelligence',
    category: 'livreur',
    roles: ['livreur'],
    label: 'Intelligence livraison IA',
    description: 'Tournées, ETA, retards, colis, navigation, vérification, performances et éco.',
    route: '/livreur/intelligence',
    icon: '🧠',
    serviceKey: 'livreurIntelligenceHubService',
  },
  {
    id: 'livreur-delivery-cold-chain',
    category: 'livreur',
    roles: ['livreur'],
    label: 'Chaîne du froid livraison',
    description: 'Capteurs IoT véhicule — température et qualité en transit.',
    route: '/livreur/delivery-cold-chain',
    icon: '🌡️',
    api: 'GET /api/livreur/delivery/cold-chain',
    serviceKey: 'deliveryColdChainService',
  },
  {
    id: 'livreur-ml',
    category: 'livreur',
    roles: ['livreur'],
    label: 'Assistant ML livreur',
    description: 'Prédiction charge et conseils tournée.',
    route: '/livreur/ml',
    icon: '🤖',
    serviceKey: 'mlService',
  },

  // —— Vétérinaire ——
  {
    id: 'vet-dashboard',
    category: 'vet',
    roles: ['vet'],
    label: 'Dashboard vétérinaire',
    description: 'Agenda, patients et indicateurs clinique.',
    route: '/vet/dashboard',
    icon: '📊',
    serviceKey: 'vetService',
  },
  {
    id: 'vet-prescriptions',
    category: 'vet',
    roles: ['vet'],
    label: 'Ordonnances',
    description: 'Création, envoi client et pharmacie.',
    route: '/vet/prescriptions',
    icon: '💊',
    api: 'GET /api/vet/prescriptions',
    serviceKey: 'vetService',
  },
  {
    id: 'vet-intelligence',
    category: 'vet',
    roles: ['vet'],
    label: 'Intelligence clinique IA',
    description: 'Diagnostic assisté, dossier médical, ordonnances, suivi prédictif, évolution santé, CR et nutrition pathologique.',
    route: '/vet/intelligence',
    icon: '🧠',
    serviceKey: 'vetIntelligenceHubService',
  },
  {
    id: 'vet-diagnostics',
    category: 'vet',
    roles: ['vet'],
    label: 'Détection précoce',
    description: 'Signaux faibles santé et alertes ML.',
    route: '/vet/diagnostics',
    icon: '🔬',
    serviceKey: 'vetService',
  },
  {
    id: 'vet-bi',
    category: 'vet',
    roles: ['vet'],
    label: 'Dashboard BI vétérinaire',
    description: 'Analyses consultations et performance clinique.',
    route: '/vet/bi',
    icon: '📈',
    serviceKey: 'vetService',
  },

  // —— Vendeur (public + espace connecté) ——
  {
    id: 'vendor-hub',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Hub vendeur',
    description: 'Découverte marketplace, commissions et inscription partenaire.',
    route: '/vendor',
    icon: '🏬',
  },
  {
    id: 'vendor-marketplace',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Marketplace PetfoodTN',
    description: 'Vendez croquettes et accessoires auprès des clients de la plateforme.',
    route: '/#partenaires',
    icon: '🛒',
  },
  {
    id: 'vendor-commissions',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Commissions & paiements',
    description: 'Taux indicatif 12 %, suivi des commissions et virements.',
    route: '/vendor#commissions',
    icon: '💰',
  },
  {
    id: 'vendor-ml-preview',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Assistant ML vendeur',
    description: 'Prévisions stock, alertes rupture et conseils promo IA.',
    route: '/vendor#ml-vendeur',
    icon: '🤖',
  },
  {
    id: 'vendor-onboarding',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Devenir partenaire',
    description: 'Animaleries, fabricants et distributeurs — demande d\'accès.',
    route: '/vendor#devenir-partenaire',
    icon: '✨',
  },
  {
    id: 'vendor-login',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Connexion vendeur',
    description: 'Accédez à votre tableau de bord boutique et commandes.',
    route: '/login',
    icon: '🔑',
    badge: 'Pro',
  },
  {
    id: 'vendor-dashboard-public',
    category: 'vendeur',
    roles: ['vendeur'],
    label: 'Tableau de bord (aperçu)',
    description: 'KPIs ventes, stock et rang marketplace — après connexion.',
    route: '/login',
    icon: '📊',
    badge: 'Connexion',
  },
  {
    id: 'vendor-dashboard',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Dashboard vendeur',
    description: 'CA, commandes, stock, commissions et assistant ML.',
    route: '/vendor/dashboard',
    icon: '📊',
    serviceKey: 'ecosystemService',
  },
  {
    id: 'vendor-products',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Mes produits',
    description: 'Catalogue boutique, prix, stock et performances.',
    route: '/vendor/products',
    icon: '🏷️',
  },
  {
    id: 'vendor-food-quality',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Qualité alimentaire IoT',
    description: 'Surveillance chaîne du froid, lots, anomalies et frigo connecté.',
    route: '/vendor/food-quality',
    icon: '🌡️',
    api: 'GET /api/vendor/food-quality/surveillance',
    serviceKey: 'coldChainQualityService',
  },
  {
    id: 'vendor-orders',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Commandes marketplace',
    description: 'Suivi des ventes, commissions et statuts de paiement.',
    route: '/vendor/orders',
    icon: '📦',
  },
  {
    id: 'vendor-returns',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Gestion des retours',
    description: 'Traiter demandes de retour et remboursements clients.',
    route: '/vendor/returns',
    icon: '↩️',
  },
  {
    id: 'vendor-communication',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Communication clients',
    description: 'Répondre aux avis, messagerie et notifications.',
    route: '/vendor/communication',
    icon: '💬',
  },
  {
    id: 'vendor-platform-services',
    category: 'vendeur',
    roles: ['vendor'],
    label: 'Catalogue services',
    description: 'Référentiel des outils vendeur PetfoodTN.',
    route: '/vendor/platform-services',
    icon: '📋',
  },

  // —— Modérateur (public + espace connecté) ——
  {
    id: 'moderator-hub',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Hub modération',
    description: 'Découverte modération communauté, avis NLP et signalements.',
    route: '/moderator',
    icon: '🛡️',
  },
  {
    id: 'moderator-reviews-public',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Modération des avis',
    description: 'Validation, masquage et analyse sentiments NLP — aperçu.',
    route: '/moderator#avis',
    icon: '⭐',
  },
  {
    id: 'moderator-complaints-public',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Réclamations & signalements',
    description: 'Traitement tickets clients, SLA et escalade — aperçu public.',
    route: '/moderator#reclamations',
    icon: '⚠️',
  },
  {
    id: 'moderator-events-public',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Événements & concours',
    description: 'Supervision inscriptions, lots et contenus événementiels.',
    route: '/moderator#evenements',
    icon: '🎪',
  },
  {
    id: 'moderator-nlp-public',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Analyse NLP',
    description: 'Détection spam, sentiment et émotion sur les avis communautaires.',
    route: '/moderator#nlp',
    icon: '🤖',
  },
  {
    id: 'moderator-login-public',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Connexion modérateur',
    description: 'Accédez au tableau de bord modération et files d\'attente.',
    route: '/login',
    icon: '🔑',
    badge: 'Pro',
  },
  {
    id: 'moderator-dashboard-public',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Tableau de bord (aperçu)',
    description: 'Files avis, réclamations et messages — après connexion.',
    route: '/login',
    icon: '📊',
    badge: 'Connexion',
  },
  {
    id: 'moderator-vendor-link',
    category: 'moderateur',
    roles: ['moderateur'],
    label: 'Espace vendeur',
    description: 'Marketplace et fournisseurs partenaires PetfoodTN.',
    route: '/vendor',
    icon: '🏬',
  },
  {
    id: 'moderator-dashboard',
    category: 'moderateur',
    roles: ['moderator'],
    label: 'Tableau de bord modération',
    description: 'Files d\'attente avis, réclamations et alertes communauté.',
    route: '/moderator/dashboard',
    icon: '🛡️',
  },
  {
    id: 'moderator-reviews',
    category: 'moderateur',
    roles: ['moderator', 'admin'],
    label: 'Modération des avis',
    description: 'Validation, masquage et analyse sentiments NLP.',
    route: '/moderator/reviews',
    icon: '⭐',
    api: 'GET /api/reviews',
    serviceKey: 'reviewService',
  },
  {
    id: 'moderator-complaints',
    category: 'moderateur',
    roles: ['moderator', 'admin'],
    label: 'Réclamations & signalements',
    description: 'Traitement tickets clients, SLA et escalade admin.',
    route: '/moderator/complaints',
    icon: '⚠️',
    api: 'GET /api/complaints',
    serviceKey: 'complaintService',
  },
  {
    id: 'moderator-events',
    category: 'moderateur',
    roles: ['moderator', 'admin'],
    label: 'Événements & concours',
    description: 'Supervision inscriptions, lots et contenus événementiels.',
    route: '/moderator/events',
    icon: '🎪',
  },
  {
    id: 'moderator-messages',
    category: 'moderateur',
    roles: ['moderator'],
    label: 'Messages signalés',
    description: 'Chat et messages communautaires à modérer.',
    route: '/moderator/messages',
    icon: '💬',
    api: 'GET /api/messages',
    serviceKey: 'messageService',
  },
  {
    id: 'moderator-users',
    category: 'admin',
    roles: ['admin'],
    label: 'Gestion utilisateurs',
    description: 'Profils, suspension et réactivation — admin uniquement.',
    route: '/admin/users',
    icon: '👤',
  },
  {
    id: 'moderator-vendors',
    category: 'admin',
    roles: ['admin'],
    label: 'Gestion vendeurs',
    description: 'Validation, vérification et suspension — admin uniquement.',
    route: '/admin/vendors',
    icon: '🏬',
  },
  {
    id: 'moderator-content',
    category: 'moderateur',
    roles: ['moderator', 'admin'],
    label: 'Modération contenu',
    description: 'Validation produits, contenus inappropriés et images.',
    route: '/moderator/content',
    icon: '🏷️',
  },
  {
    id: 'moderator-reports',
    category: 'moderateur',
    roles: ['moderator'],
    label: 'Signalements & litiges',
    description: 'Litiges commandes et détection faux avis NLP.',
    route: '/moderator/reports',
    icon: '⚖️',
  },
  {
    id: 'moderator-refunds',
    category: 'moderateur',
    roles: ['moderator'],
    label: 'Litiges remboursements',
    description: 'Réclamations, contestations et vérification fraude.',
    route: '/moderator/refunds',
    icon: '💸',
    serviceKey: 'refundService',
  },
  {
    id: 'moderator-analytics',
    category: 'moderateur',
    roles: ['moderator', 'admin'],
    label: 'Rapports modération',
    description: 'Stats utilisateurs, activité vendeurs et historique.',
    route: '/moderator/analytics',
    icon: '📈',
  },
  {
    id: 'moderator-platform-services',
    category: 'moderateur',
    roles: ['moderator'],
    label: 'Catalogue services',
    description: 'Référentiel des espaces et droits par rôle.',
    route: '/moderator/platform-services',
    icon: '📋',
  },
];

export const getServicesForRole = (role) => {
  const r = String(role || 'client').toLowerCase();
  return PLATFORM_SERVICES.filter((s) => s.roles.includes(r));
};

export const getServicesByCategory = (role) => {
  const services = getServicesForRole(role);
  const cats = PLATFORM_SERVICE_CATEGORIES.filter((c) =>
    services.some((s) => s.category === c.id),
  );
  return cats.map((cat) => ({
    ...cat,
    services: services.filter((s) => s.category === cat.id),
  }));
};

export const getBookableServices = (role = 'client') =>
  getServicesForRole(role).filter((s) => s.bookable);

export const findPlatformService = (id) =>
  PLATFORM_SERVICES.find((s) => s.id === id) || null;

/** Catégories visibles sur la page marketing publique (sans admin / livreur / vet). */
export const PUBLIC_MARKETING_CATEGORIES = [
  'boutique', 'sante', 'nutrition', 'soins', 'iot', 'livraison', 'ecosystem', 'ia',
];

export const getPublicMarketingCatalog = () => {
  const services = getServicesForRole('client').filter((s) =>
    PUBLIC_MARKETING_CATEGORIES.includes(s.category),
  );
  const cats = PLATFORM_SERVICE_CATEGORIES.filter((c) =>
    PUBLIC_MARKETING_CATEGORIES.includes(c.id),
  );
  return cats.map((cat) => ({
    ...cat,
    services: services.filter((s) => s.category === cat.id),
  })).filter((c) => c.services.length > 0);
};

/** @deprecated Espace visiteur retiré — retourne un catalogue vide. */
export const getVisitorCatalog = () => [];

/** Catalogue hub vendeur public (sans authentification). */
export const getVendorPublicCatalog = () =>
  getServicesByCategory('vendeur')
    .map((cat) => ({
      ...cat,
      services: cat.services.filter((s) => s.roles.includes('vendeur')),
    }))
    .filter((cat) => cat.services.length > 0);

/** Catalogue hub modérateur public (sans authentification). */
export const getModeratorPublicCatalog = () =>
  getServicesByCategory('moderateur')
    .map((cat) => ({
      ...cat,
      services: cat.services.filter((s) => s.roles.includes('moderateur')),
    }))
    .filter((cat) => cat.services.length > 0);

/** Acteurs affichés sur la landing (tous les rôles métier). */
export const PLATFORM_ACTOR_ROLES = [
  { id: 'client', label: 'Client', icon: '🐾', publicAccess: false },
  { id: 'vet', label: 'Vétérinaire', icon: '🩺', publicAccess: false },
  { id: 'livreur', label: 'Livreur', icon: '🛵', publicAccess: false },
  { id: 'vendor', label: 'Vendeur', icon: '🏬', publicAccess: true },
  { id: 'moderator', label: 'Modérateur', icon: '🛡️', publicAccess: true },
  { id: 'admin', label: 'Administrateur', icon: '⚙️', publicAccess: false },
];

export const MARKETING_STATS = [
  { value: '50+', label: 'Services intégrés' },
  { value: '8', label: 'Espèces nutrition' },
  { value: '5★', label: 'Avis produits & services' },
  { value: '24/7', label: 'Assistant & NLP' },
];
