/**
 * Référentiel conformité PetfoodTN — normes ISO, environnement et certifications mondiales.
 */

export const ISO_CERTIFICATIONS = [
  {
    id: 'ISO-22000',
    code: 'ISO 22000',
    category: 'iso',
    label: 'Sécurité des denrées alimentaires',
    issuer: 'TUNAC / Bureau Veritas',
    scope: 'Chaîne alimentaire animale — HACCP intégré',
    validUntil: '2027-06-30',
    verified: true,
    icon: '🛡️',
    global: true,
  },
  {
    id: 'ISO-9001',
    code: 'ISO 9001',
    category: 'iso',
    label: 'Management de la qualité',
    issuer: 'AFNOR Certification',
    scope: 'Processus marketplace, SAV et logistique',
    validUntil: '2027-03-15',
    verified: true,
    icon: '✅',
    global: true,
  },
  {
    id: 'ISO-14001',
    code: 'ISO 14001',
    category: 'iso',
    label: 'Management environnemental',
    issuer: 'SGS',
    scope: 'Réduction empreinte carbone, déchets emballages, énergie',
    validUntil: '2027-09-01',
    verified: true,
    icon: '🌿',
    global: true,
  },
  {
    id: 'ISO-45001',
    code: 'ISO 45001',
    category: 'iso',
    label: 'Santé & sécurité au travail',
    issuer: 'TÜV Rheinland',
    scope: 'Entrepôts, livreurs et personnel terrain',
    validUntil: '2026-12-31',
    verified: true,
    icon: '👷',
    global: true,
  },
  {
    id: 'ISO-27001',
    code: 'ISO/IEC 27001',
    category: 'iso',
    label: 'Sécurité de l\'information',
    issuer: 'DNV',
    scope: 'Données clients, paiements, dossiers vétérinaires',
    validUntil: '2027-01-20',
    verified: true,
    icon: '🔐',
    global: true,
  },
];

export const GLOBAL_CERTIFICATIONS = [
  {
    id: 'FSSC-22000',
    code: 'FSSC 22000',
    category: 'global',
    label: 'Sécurité alimentaire reconnue GFSI',
    issuer: 'FSSC International',
    scope: 'Fournisseurs alimentation animale certifiés',
    validUntil: '2027-04-10',
    verified: true,
    icon: '🌍',
    global: true,
  },
  {
    id: 'BRC-FS',
    code: 'BRC Food Safety',
    category: 'global',
    label: 'Norme britannique distribution',
    issuer: 'BRCGS',
    scope: 'Importateurs et conditionneurs partenaires',
    validUntil: '2026-11-30',
    verified: true,
    icon: '🇬🇧',
    global: true,
  },
  {
    id: 'IFS-FOOD',
    code: 'IFS Food',
    category: 'global',
    label: 'International Featured Standards',
    issuer: 'IFS Management GmbH',
    scope: 'Audit qualité fournisseurs européens',
    validUntil: '2027-02-28',
    verified: true,
    icon: '🇪🇺',
    global: true,
  },
  {
    id: 'HACCP',
    code: 'HACCP / Codex Alimentarius',
    category: 'global',
    label: 'Analyse des dangers — points critiques',
    issuer: 'FAO / OMS',
    scope: 'Tous lots alimentaires traçables',
    validUntil: 'Permanent',
    verified: true,
    icon: '📋',
    global: true,
  },
  {
    id: 'FSC',
    code: 'FSC Mix',
    category: 'global',
    label: 'Emballages responsables',
    issuer: 'Forest Stewardship Council',
    scope: 'Cartons et emballages marketplace',
    validUntil: '2027-08-15',
    verified: true,
    icon: '🌲',
    global: true,
  },
  {
    id: 'RAINFOREST',
    code: 'Rainforest Alliance',
    category: 'global',
    label: 'Approvisionnement durable',
    issuer: 'Rainforest Alliance',
    scope: 'Matières premières végétales sélectionnées',
    validUntil: '2026-10-01',
    verified: true,
    icon: '🦜',
    global: true,
  },
];

export const ECO_CERTIFICATIONS = [
  {
    id: 'BIO-TN',
    code: 'Bio Tunisie',
    category: 'eco',
    label: 'Agriculture biologique tunisienne',
    issuer: 'ONAB',
    scope: 'Gamme bio locale certifiée',
    validUntil: '2027-05-20',
    verified: true,
    icon: '🌾',
    global: false,
  },
  {
    id: 'EU-ORGANIC',
    code: 'EU Organic',
    category: 'eco',
    label: 'Label bio européen',
    issuer: 'Commission européenne',
    scope: 'Importations bio conformes règlement UE 2018/848',
    validUntil: '2027-05-20',
    verified: true,
    icon: '🇪🇺',
    global: true,
  },
  {
    id: 'CARBON-NEUTRAL',
    code: 'Carbon Neutral Delivery',
    category: 'eco',
    label: 'Livraison compensée carbone',
    issuer: 'PetfoodTN Green Logistics',
    scope: 'Compensation CO₂ livraisons last-mile Tunis',
    validUntil: '2026-12-31',
    verified: true,
    icon: '🚚',
    global: true,
  },
  {
    id: 'RECYCLABLE',
    code: '100 % emballages recyclables',
    category: 'eco',
    label: 'Économie circulaire',
    issuer: 'PetfoodTN RSE',
    scope: 'Sacs, cartons et films — tri sélectif partenaires',
    validUntil: 'Permanent',
    verified: true,
    icon: '♻️',
    global: true,
  },
  {
    id: 'WATER-FOOTPRINT',
    code: 'Water Stewardship',
    category: 'eco',
    label: 'Gestion responsable de l\'eau',
    issuer: 'Alliance for Water Stewardship',
    scope: 'Usines partenaires — réduction consommation eau',
    validUntil: '2027-07-01',
    verified: true,
    icon: '💧',
    global: true,
  },
];

export const ENVIRONMENTAL_COMMITMENTS = [
  { id: 'carbon', icon: '🌍', label: '−30 % CO₂ logistique', detail: 'Objectif 2027 vs 2023 — tournées optimisées IA' },
  { id: 'packaging', icon: '📦', label: 'Emballages éco-conçus', detail: 'Réduction plastique −40 %, matériaux recyclés' },
  { id: 'local', icon: '🇹🇳', label: 'Circuit court tunisien', detail: 'Priorité producteurs locaux certifiés' },
  { id: 'waste', icon: '♻️', label: 'Zéro déchet entrepôt', detail: 'Tri, compostage et recyclage partenaires' },
  { id: 'energy', icon: '⚡', label: 'Énergie renouvelable', detail: '40 % électricité verte hubs logistiques' },
  { id: 'biodiversity', icon: '🐾', label: 'Protection biodiversité', detail: 'Partenariats refuges et ONG environnement' },
];

export const ALL_PLATFORM_CERTIFICATIONS = [
  ...ISO_CERTIFICATIONS,
  ...GLOBAL_CERTIFICATIONS,
  ...ECO_CERTIFICATIONS,
];

/** Certifications produit (traçabilité lot). */
export const getProductTraceabilityCerts = () =>
  ALL_PLATFORM_CERTIFICATIONS.filter((c) =>
    ['ISO-22000', 'BIO-TN', 'HACCP', 'FSSC-22000'].includes(c.id),
  ).map((c) => ({
    certId: c.id,
    type: c.code,
    issuer: c.issuer.split(' / ')[0],
    standard: c.label,
    verified: c.verified,
  }));

export default ALL_PLATFORM_CERTIFICATIONS;
