/** Matrice officielle des capacités PetfoodTN par acteur. */

export const ROLE_CAPABILITIES = [
  {
    id: 'visitor',
    icon: '👀',
    label: 'Visiteur',
    auth: false,
    features: [
      { label: 'Consulter les produits', route: '/visitor/products' },
      { label: 'Rechercher des produits', route: '/visitor/products' },
      { label: 'Conseils nutritionnels', route: '/visitor/info?tab=nutrition' },
      { label: "S'inscrire", route: '/register' },
    ],
  },
  {
    id: 'client',
    icon: '🛒',
    label: 'Client',
    auth: true,
    role: 'client',
    features: [
      { label: 'Gérer son profil', route: '/client-profile' },
      { label: 'Gérer ses animaux', route: '/client-pets' },
      { label: 'Commander des produits', route: '/client-products' },
      { label: 'Publier un besoin d\'achat', route: '/client-purchase-needs' },
      { label: 'Payer en ligne', route: '/checkout' },
      { label: 'Suivre les commandes', route: '/client-orders' },
      { label: 'Recommandations nutrition', route: '/pet-calories' },
      { label: 'RDV vétérinaire', route: '/veterinary' },
      { label: 'Laisser un avis', route: '/client-reviews' },
      { label: 'Demander un retour', route: '/client-returns' },
    ],
  },
  {
    id: 'vendor',
    icon: '🏪',
    label: 'Vendeur',
    auth: true,
    role: 'vendor',
    features: [
      { label: 'Ajouter / modifier produits', route: '/vendor/products' },
      { label: 'Gérer le stock', route: '/vendor/products' },
      { label: 'Gérer les commandes', route: '/vendor/orders' },
      { label: 'Consulter les ventes', route: '/vendor/sales' },
      { label: 'Dashboard BI', route: '/vendor/bi' },
      { label: 'Répondre aux avis', route: '/vendor/communication' },
      { label: 'Gérer les retours', route: '/vendor/returns' },
    ],
  },
  {
    id: 'vet',
    icon: '👨‍⚕️',
    label: 'Vétérinaire',
    auth: true,
    role: 'vet',
    features: [
      { label: 'Gérer les rendez-vous', route: '/vet/calendar' },
      { label: 'Dossiers animaux', route: '/vet/medical-dossiers' },
      { label: 'Prescriptions', route: '/vet/prescriptions' },
      { label: 'Téléconsultations', route: '/vet/teleconsult' },
      { label: 'Conseils nutritionnels', route: '/vet/nutrition' },
      { label: 'Dashboard BI', route: '/vet/bi' },
    ],
  },
  {
    id: 'livreur',
    icon: '🚚',
    label: 'Livreur',
    auth: true,
    role: 'livreur',
    features: [
      { label: 'Consulter les livraisons', route: '/livreur/orders' },
      { label: 'Mettre à jour le statut', route: '/livreur/orders' },
      { label: 'Confirmer la livraison', route: '/livreur/orders' },
      { label: 'Dashboard BI', route: '/livreur/bi' },
    ],
  },
  {
    id: 'moderator',
    icon: '🛡️',
    label: 'Modérateur',
    auth: true,
    role: 'moderator',
    features: [
      { label: 'Valider les produits', route: '/moderator/content' },
      { label: 'Modérer les avis', route: '/moderator/reviews' },
      { label: 'Traiter les signalements', route: '/moderator/reports' },
      { label: 'Litiges remboursements', route: '/moderator/refunds' },
      { label: 'Suspendre des comptes clients', route: '/moderator/users' },
      { label: 'Dashboard BI', route: '/moderator/bi' },
    ],
  },
  {
    id: 'admin',
    icon: '⚙️',
    label: 'Administrateur',
    auth: true,
    role: 'admin',
    features: [
      { label: 'Gérer les utilisateurs', route: '/admin/users' },
      { label: 'Gérer les vendeurs', route: '/admin/vendors' },
      { label: 'Gérer les vétérinaires', route: '/admin/vets' },
      { label: 'Gérer les catégories', route: '/admin/categories' },
      { label: 'Gérer les remboursements', route: '/admin/refunds' },
      { label: 'Gérer les promotions', route: '/admin/promotions' },
      { label: 'Consulter les statistiques', route: '/admin/dashboard' },
      { label: 'Dashboard BI / Power BI', route: '/admin/powerbi' },
      { label: 'Configurer la plateforme', route: '/admin/system' },
    ],
  },
  {
    id: 'support',
    icon: '📞',
    label: 'Service Client',
    auth: true,
    role: 'support',
    features: [
      { label: 'Gérer les réclamations', route: '/support/complaints' },
      { label: 'Suivre les tickets', route: '/support/tickets' },
      { label: 'Assister les utilisateurs', route: '/support/assist' },
      { label: 'Traiter les retours', route: '/support/returns' },
    ],
  },
];
