/** Matrice officielle des capacités PetfoodTN par acteur. */

export const ROLE_CAPABILITIES = [
  {
    id: 'client',
    icon: '🛒',
    label: 'Client',
    auth: true,
    role: 'client',
    features: [
      { label: 'Gérer son profil', route: '/client-profile' },
      { label: 'Gérer ses animaux', route: '/client-pets' },
      { label: 'Commander des produits', route: '/client-products' },
      { label: 'Publier un besoin d\'achat', route: '/client-purchase-needs' },
      { label: 'Payer en ligne', route: '/checkout' },
      { label: 'Suivre les commandes', route: '/client-orders' },
      { label: 'Recommandations nutrition', route: '/pet-calories' },
      { label: 'RDV vétérinaire', route: '/veterinary' },
      { label: 'Laisser un avis', route: '/client-reviews' },
      { label: 'Demander un retour', route: '/client-returns' },
    ],
  },
  {
    id: 'vendor',
    icon: '🏪',
    label: 'Vendeur',
    auth: true,
    role: 'vendor',
    features: [
      { label: 'Ajouter / modifier produits', route: '/vendor/products' },
      { label: 'Gérer le stock', route: '/vendor/products' },
      { label: 'Gérer les commandes', route: '/vendor/orders' },
      { label: 'Consulter les ventes', route: '/vendor/sales' },
      { label: 'Répondre aux avis', route: '/vendor/communication' },
      { label: 'Gérer les retours', route: '/vendor/returns' },
    ],
  },
  {
    id: 'vet',
    icon: '👨‍⚕️',
    label: 'Vétérinaire',
    auth: true,
    role: 'vet',
    features: [
      { label: 'Gérer les rendez-vous', route: '/vet/calendar' },
      { label: 'Dossiers animaux', route: '/vet/medical-dossiers' },
      { label: 'Prescriptions', route: '/vet/prescriptions' },
      { label: 'Conseils nutritionnels', route: '/vet/nutrition' },
      { label: 'Ma clinique', route: '/vet/clinic' },
    ],
  },
  {
    id: 'livreur',
    icon: '🚚',
    label: 'Livreur',
    auth: true,
    role: 'livreur',
    features: [
      { label: 'Consulter les livraisons', route: '/livreur/orders' },
      { label: 'Mettre à jour le statut', route: '/livreur/orders' },
      { label: 'Confirmer la livraison', route: '/livreur/orders' },
      { label: 'Mes gains', route: '/livreur/earnings' },
    ],
  },
  {
    id: 'moderator',
    icon: '🛡️',
    label: 'Modérateur',
    auth: true,
    role: 'moderator',
    features: [
      { label: 'Valider les produits', route: '/moderator/content' },
      { label: 'Modérer les avis', route: '/moderator/reviews' },
      { label: 'Traiter les signalements', route: '/moderator/reports' },
      { label: 'Litiges remboursements', route: '/moderator/refunds' },
      { label: 'Suspendre des comptes clients', route: '/moderator/users' },
    ],
  },
  {
    id: 'stock_manager',
    icon: '📦',
    label: 'Gestionnaire de stock',
    auth: true,
    role: 'stock_manager',
    features: [
      { label: 'Gérer le stock', route: '/admin/stock' },
      { label: 'Alertes rupture', route: '/admin/stock-bi' },
      { label: 'Réapprovisionnement', route: '/admin/stock' },
      { label: 'Inventaire produits', route: '/admin/products' },
    ],
  },
  {
    id: 'admin',
    icon: '⚙️',
    label: 'Administrateur',
    auth: true,
    role: 'admin',
    features: [
      { label: 'Gérer les utilisateurs', route: '/admin/users' },
      { label: 'Gérer les vendeurs', route: '/admin/vendors' },
      { label: 'Gérer les vétérinaires', route: '/admin/vets' },
      { label: 'Gérer les catégories', route: '/admin/categories' },
      { label: 'Gérer les remboursements', route: '/admin/refunds' },
      { label: 'Gérer les promotions', route: '/admin/promotions' },
      { label: 'Marketing digital', route: '/admin/digital-marketing' },
      { label: 'Consulter les statistiques', route: '/admin/dashboard' },
      { label: 'Dashboard BI / Power BI', route: '/admin/powerbi' },
      { label: 'Configurer la plateforme', route: '/admin/system' },
    ],
  },
];
