apiVersion: v1
kind: Secret
metadata:
  name: petfood-backend-secrets
  namespace: petfoodtn
type: Opaque
stringData:
  DATABASE_URL: postgresql://petfood:CHANGE_ME@petfood-postgres:5432/petfood?schema=public
  JWT_SECRET: change-me-super-secret-jwt-key-at-least-32-chars
  DEMO_MODE: 'false'
  CORS_ORIGINS: https://app.petfoodtn.tn
  FASTAPI_URL: http://petfood-ml:8000
  MQTT_BROKER_URL: mqtt://petfood-mqtt:1883
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petfood-postgres
  namespace: petfoodtn
spec:
  serviceName: petfood-postgres
  replicas: 1
  selector:
    matchLabels:
      app: petfood-postgres
  template:
    metadata:
      labels:
        app: petfood-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: petfood
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petfood-backend-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: petfood
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: petfood-postgres
  namespace: petfoodtn
spec:
  selector:
    app: petfood-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
