/** Styles partagés pages login / mot de passe oublié */
import { LOGIN_BACKGROUND } from './platformImages';

export const authPageStyles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    backgroundImage: `url('${LOGIN_BACKGROUND}')`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(135deg, rgba(0,0,0,0.45) 0%, rgba(0,0,0,0.25) 100%)',
    zIndex: 0,
  },
  card: {
    background: 'rgba(255, 255, 255, 0.92)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRadius: '24px',
    padding: '40px 32px',
    width: '100%',
    maxWidth: '440px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.15)',
    position: 'relative',
    zIndex: 1,
  },
  title: { fontSize: '22px', fontWeight: 800, color: '#065f46', margin: '0 0 8px' },
  subtitle: { fontSize: '14px', color: '#6b7280', margin: '0 0 24px', lineHeight: 1.5 },
  label: { display: 'block', fontSize: '13px', fontWeight: 600, color: '#374151', marginBottom: '6px' },
  fieldError: { color: '#dc2626', fontSize: '12px', marginTop: '6px' },
  errorBox: {
    background: 'rgba(254, 226, 226, 0.9)',
    border: '1px solid rgba(252, 165, 165, 0.5)',
    color: '#b91c1c',
    padding: '12px 16px',
    borderRadius: '12px',
    fontSize: '13px',
    marginBottom: '16px',
  },
  successBox: {
    background: 'rgba(209, 250, 229, 0.95)',
    border: '1px solid #6ee7b7',
    color: '#047857',
    padding: '12px 16px',
    borderRadius: '12px',
    fontSize: '13px',
    marginBottom: '16px',
    lineHeight: 1.5,
  },
  infoBox: {
    background: '#eff6ff',
    border: '1px solid #bfdbfe',
    color: '#1d4ed8',
    padding: '12px 14px',
    borderRadius: '12px',
    fontSize: '12px',
    marginTop: '12px',
    lineHeight: 1.5,
    wordBreak: 'break-all',
  },
  submitBtn: {
    width: '100%',
    padding: '14px',
    background: 'linear-gradient(135deg, #10b981, #059669)',
    color: 'white',
    border: 'none',
    borderRadius: '14px',
    fontSize: '15px',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 8px 20px rgba(16, 185, 129, 0.3)',
    marginTop: '8px',
  },
  linkRow: { textAlign: 'center', marginTop: '18px', fontSize: '14px', color: '#475569' },
  link: { color: '#10b981', fontWeight: 700, textDecoration: 'none' },
  spinner: {
    width: '18px',
    height: '18px',
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: 'white',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    display: 'inline-block',
  },
};

export const authInputStyle = (hasError) => ({
  width: '100%',
  padding: '14px 16px',
  borderRadius: '14px',
  border: `2px solid ${hasError ? '#f87171' : '#e5e7eb'}`,
  background: 'white',
  fontSize: '14px',
  color: '#1f2937',
  outline: 'none',
  boxSizing: 'border-box',
});

/** Champ mot de passe avec bouton afficher/masquer à droite */
export const authPasswordInputStyle = (hasError) => ({
  ...authInputStyle(hasError),
  padding: '14px 44px 14px 16px',
});
