const hoursAgo = (h) => new Date(Date.now() - h * 3600000).toISOString();

const mkHistory = (base, count = 12) => {
  const hist = [];
  for (let i = count - 1; i >= 0; i -= 1) {
    hist.push({
      temperatureC: Math.round((base.temp + (Math.random() - 0.5) * 2) * 10) / 10,
      humidityPct: Math.round(base.hum + (Math.random() - 0.5) * 4),
      luminosityLux: Math.round(base.lux + (Math.random() - 0.5) * 20),
      airQualityPpm: Math.round(base.air + (Math.random() - 0.5) * 40),
      recordedAt: hoursAgo(i * 0.5),
    });
  }
  return hist.reverse();
};

export const DEMO_COLD_CHAIN_PACK = {
  mode: 'demo',
  zones: [
    {
      id: 'zone-wh-1',
      type: 'warehouse',
      name: 'Entrepôt Tunis Nord',
      location: 'Ariana',
      status: 'online',
      vendorId: null,
      currentReading: {
        temperatureC: 19.2,
        humidityPct: 48,
        luminosityLux: 120,
        airQualityPpm: 420,
        lidOpen: false,
        coolingActive: true,
        recordedAt: hoursAgo(0.05),
      },
      history: mkHistory({ temp: 19, hum: 48, lux: 120, air: 420 }),
      targetTempC: 18,
      autoControl: true,
    },
    {
      id: 'zone-vh-1',
      type: 'vehicle',
      name: 'Camion livraison #12',
      location: 'En route — Sfax',
      status: 'online',
      vendorId: 'vendor-demo-1',
      currentReading: {
        temperatureC: 24.8,
        humidityPct: 58,
        luminosityLux: 340,
        airQualityPpm: 510,
        lidOpen: false,
        coolingActive: false,
        recordedAt: hoursAgo(0.08),
      },
      history: mkHistory({ temp: 23, hum: 55, lux: 300, air: 500 }),
      targetTempC: 16,
      autoControl: true,
    },
    {
      id: 'zone-fr-1',
      type: 'fridge',
      name: 'Frigo fraîcheur — Marketplace',
      location: 'Stand La Marsa',
      status: 'online',
      vendorId: 'vendor-demo-1',
      currentReading: {
        temperatureC: 4.5,
        humidityPct: 52,
        luminosityLux: 15,
        airQualityPpm: 380,
        lidOpen: false,
        coolingActive: true,
        recordedAt: hoursAgo(0.03),
      },
      history: mkHistory({ temp: 4.5, hum: 52, lux: 12, air: 380 }),
      targetTempC: 4,
      autoControl: true,
    },
    {
      id: 'zone-fd-1',
      type: 'feeder',
      name: 'Distributeur Max — Salon',
      location: 'Client IoT',
      status: 'online',
      vendorId: null,
      currentReading: {
        temperatureC: 24.2,
        humidityPct: 58,
        luminosityLux: 95,
        airQualityPpm: 445,
        lidOpen: false,
        coolingActive: true,
        recordedAt: hoursAgo(0.1),
      },
      history: mkHistory({ temp: 24, hum: 56, lux: 90, air: 440 }),
      targetTempC: 20,
      autoControl: false,
    },
    {
      id: 'zone-wh-2',
      type: 'warehouse',
      name: 'Entrepôt Sousse',
      location: 'Sousse',
      status: 'online',
      vendorId: 'vendor-demo-1',
      currentReading: {
        temperatureC: 20.1,
        humidityPct: 44,
        luminosityLux: 90,
        airQualityPpm: 390,
        lidOpen: true,
        coolingActive: true,
        recordedAt: hoursAgo(0.15),
      },
      history: mkHistory({ temp: 20, hum: 44, lux: 85, air: 390 }),
      targetTempC: 18,
      autoControl: true,
    },
  ],
  batches: [
    {
      id: 'lot-1',
      code: 'LOT-2026-0312',
      productName: 'Croquettes Premium Chien 15 kg',
      zoneId: 'zone-wh-1',
      zoneIds: ['zone-wh-1'],
      expiryDate: '2026-09-15',
      ageDays: 45,
      maxShelfDays: 365,
      daysToExpiry: 92,
      storageScore: 88,
      quantity: 240,
    },
    {
      id: 'lot-2',
      code: 'LOT-2026-0288',
      productName: 'Pâtée chat saumon 24 boîtes',
      zoneId: 'zone-fr-1',
      zoneIds: ['zone-fr-1'],
      expiryDate: '2026-05-20',
      ageDays: 62,
      maxShelfDays: 180,
      daysToExpiry: 18,
      storageScore: 72,
      quantity: 48,
    },
    {
      id: 'lot-3',
      code: 'LOT-2026-0199',
      productName: 'Friandises dentaires chien',
      zoneId: 'zone-vh-1',
      zoneIds: ['zone-vh-1'],
      expiryDate: '2026-08-01',
      ageDays: 90,
      maxShelfDays: 270,
      daysToExpiry: 47,
      storageScore: 58,
      quantity: 120,
    },
    {
      id: 'lot-4',
      code: 'LOT-2026-0401',
      productName: 'Aliment chat stérilisé 7 kg',
      zoneId: 'zone-wh-2',
      zoneIds: ['zone-wh-2'],
      expiryDate: '2026-11-30',
      ageDays: 12,
      maxShelfDays: 365,
      daysToExpiry: 168,
      storageScore: 91,
      quantity: 180,
    },
    {
      id: 'lot-5',
      code: 'LOT-2026-0333',
      productName: 'Croquettes Max — bac distributeur',
      zoneId: 'zone-fd-1',
      zoneIds: ['zone-fd-1'],
      expiryDate: '2026-07-10',
      ageDays: 30,
      maxShelfDays: 120,
      daysToExpiry: 55,
      storageScore: 76,
      quantity: 3,
    },
  ],
};

export const getVendorColdChainPack = (vendorId = 'vendor-demo-1') => ({
  ...DEMO_COLD_CHAIN_PACK,
  zones: DEMO_COLD_CHAIN_PACK.zones.filter(
    (z) => !z.vendorId || z.vendorId === vendorId,
  ),
  batches: DEMO_COLD_CHAIN_PACK.batches.filter(
    (b) => DEMO_COLD_CHAIN_PACK.zones.some(
      (z) => (z.id === b.zoneId || b.zoneIds?.includes(z.id)) && (!z.vendorId || z.vendorId === vendorId),
    ),
  ),
});

export default DEMO_COLD_CHAIN_PACK;
