/** Données démo — remboursements & politique retour (tous acteurs). */

const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();
const hoursAgo = (h) => new Date(Date.now() - h * 3600000).toISOString();

export const REFUND_STATUS_LABELS = {
  pending: 'En attente vendeur',
  approved: 'Approuvé — retour attendu',
  rejected: 'Refusé par vendeur',
  awaiting_return: 'Retour en cours',
  return_received: 'Produit reçu',
  refund_validated: 'Remboursement validé',
  refunded: 'Remboursé',
  disputed: 'Litige — modération',
  moderator_review: 'Analyse modérateur',
  moderator_resolved: 'Décision modérateur',
  admin_forced: 'Remboursement forcé (admin)',
  cancelled: 'Transaction annulée (admin)',
  fraud_flagged: 'Fraude signalée',
};

export const REFUND_REASON_LABELS = {
  damaged: 'Produit endommagé',
  wrong_product: 'Mauvais article',
  not_as_described: 'Non conforme à la description',
  late_delivery: 'Livraison tardive',
  changed_mind: 'Changement d\'avis',
  other: 'Autre',
};

/** Motifs sans retour physique (remboursement direct). */
export const NO_RETURN_REASON_CATEGORIES = ['late_delivery'];

export const isNoReturnRefund = (reasonCategory) =>
  NO_RETURN_REASON_CATEGORIES.includes(reasonCategory);

export const DEMO_REFUND_POLICY = {
  returnWindowDays: 14,
  refundProcessingDays: 5,
  moderatorEscalationDays: 3,
  autoRefundThresholdDt: 50,
  requirePhotoEvidence: true,
  partialRefundEnabled: true,
  allowChangedMind: false,
  vendorMustConfirmReceipt: true,
  lateDeliveryGraceDays: 2,
  lateDeliveryAutoApprove: true,
  lateDeliveryMaxDays: 30,
  updatedAt: daysAgo(3),
};

const hist = (action, actor, actorRole, note = '') => ({
  at: new Date().toISOString(),
  action,
  actor,
  actorRole,
  note,
});

export const DEMO_REFUNDS = [
  {
    id: 'ref-1',
    orderId: 'CMD-8775',
    clientName: 'Leila S.',
    vendorName: 'Leila Mansouri',
    productName: 'Fontaine eau chat 2 L',
    amount: 89,
    reason: 'Produit défectueux — pompe ne fonctionne pas',
    reasonCategory: 'damaged',
    status: 'pending',
    returnReceived: false,
    fraudScore: 0.08,
    disputed: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    history: [hist('request_created', 'Leila S.', 'client', 'Demande de remboursement')],
  },
  {
    id: 'ref-2',
    orderId: 'CMD-8720',
    clientName: 'Omar B.',
    vendorName: 'Leila Mansouri',
    productName: 'Jouet corde résistant',
    amount: 24,
    reason: 'Article différent de la photo',
    reasonCategory: 'wrong_product',
    status: 'awaiting_return',
    returnReceived: false,
    fraudScore: 0.12,
    disputed: false,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
    history: [
      hist('request_created', 'Omar B.', 'client'),
      hist('vendor_approved', 'Leila Mansouri', 'vendor', 'Motif vérifié — retour accepté'),
    ],
  },
  {
    id: 'ref-3',
    orderId: 'CMD-8699',
    clientName: 'Ines M.',
    vendorName: 'Ridha Ben Ammar',
    productName: 'Croquettes premium chien 15 kg',
    amount: 156,
    reason: 'Changement d\'avis',
    reasonCategory: 'changed_mind',
    status: 'disputed',
    returnReceived: false,
    fraudScore: 0.15,
    disputed: true,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
    history: [
      hist('request_created', 'Ines M.', 'client'),
      hist('vendor_rejected', 'Ridha Ben Ammar', 'vendor', 'Hors délai politique retour'),
      hist('client_disputed', 'Ines M.', 'client', 'Contestation de la décision'),
    ],
  },
  {
    id: 'ref-4',
    orderId: 'CMD-8650',
    clientName: 'Amira B.',
    vendorName: 'Leila Mansouri',
    productName: 'Pâtée chat saumon x6',
    amount: 42,
    reason: 'Boîtes enfoncées à la livraison',
    reasonCategory: 'damaged',
    status: 'return_received',
    returnReceived: true,
    returnReceivedAt: daysAgo(1),
    fraudScore: 0.05,
    disputed: false,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
    history: [
      hist('request_created', 'Amira B.', 'client'),
      hist('vendor_approved', 'Leila Mansouri', 'vendor'),
      hist('return_received', 'Leila Mansouri', 'vendor', 'Colis reçu en bon état'),
    ],
  },
  {
    id: 'ref-5',
    orderId: 'CMD-8601',
    clientName: 'Karim M.',
    vendorName: 'Ridha Ben Ammar',
    productName: 'Litière agglomérante 10 L',
    amount: 35,
    reason: 'Colis non reçu après 6 jours de retard',
    reasonCategory: 'late_delivery',
    delayDays: 6,
    noReturnRequired: true,
    status: 'refunded',
    returnReceived: false,
    fraudScore: 0.03,
    disputed: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(8),
    history: [
      hist('request_created', 'Karim M.', 'client'),
      hist('vendor_approved_no_return', 'Ridha Ben Ammar', 'vendor', 'Retard confirmé — sans retour physique'),
      hist('refund_validated', 'Ridha Ben Ammar', 'vendor'),
      hist('refunded', 'Système', 'system', 'Virement 35 DT'),
    ],
  },
  {
    id: 'ref-8',
    orderId: 'CMD-8791',
    clientName: 'Karim M.',
    vendorName: 'Pets & Co Sfax',
    productName: 'Croquettes chat 3 kg',
    amount: 42,
    reason: 'Livraison prévue sous 3 jours, reçue après 7 jours',
    reasonCategory: 'late_delivery',
    delayDays: 7,
    noReturnRequired: true,
    status: 'pending',
    returnReceived: false,
    fraudScore: 0.04,
    disputed: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    history: [hist('request_created', 'Karim M.', 'client', 'Retard livraison > 5 jours')],
  },
  {
    id: 'ref-6',
    orderId: 'CMD-8580',
    clientName: 'Youssef G.',
    vendorName: 'Leila Mansouri',
    productName: 'Croquettes chiot 8 kg',
    amount: 120,
    reason: 'Multiples demandes suspectes',
    reasonCategory: 'other',
    status: 'fraud_flagged',
    returnReceived: false,
    fraudScore: 0.91,
    disputed: true,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(5),
    history: [
      hist('request_created', 'Youssef G.', 'client'),
      hist('fraud_flagged', 'Système NLP', 'system', 'Score fraude 91 %'),
      hist('moderator_review', 'Nour Modération', 'moderator'),
    ],
  },
  {
    id: 'ref-7',
    orderId: 'CMD-8555',
    clientName: 'Salma K.',
    vendorName: 'Boutique Nour Pets',
    productName: 'Harnais chien réglable',
    amount: 55,
    reason: 'Litige complexe — double débit',
    reasonCategory: 'other',
    status: 'admin_forced',
    returnReceived: true,
    fraudScore: 0.2,
    disputed: true,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
    history: [
      hist('request_created', 'Salma K.', 'client'),
      hist('disputed', 'Salma K.', 'client'),
      hist('admin_forced_refund', 'Ghassen Admin', 'admin', 'Remboursement forcé après analyse'),
    ],
  },
];

export const DEMO_MODERATOR_REFUND_DISPUTES = DEMO_REFUNDS.filter(
  (r) => r.disputed || r.status === 'fraud_flagged' || r.status === 'moderator_review' || r.status === 'disputed',
);
